// Jonggrang orchestration plugin for OpenCode
// Generated by: jonggrang init — do not edit manually
const projectRoot = require('path').resolve(__dirname, '../..');
let createPlugin;
try {
  createPlugin = require('jonggrang/hooks/opencode/plugin').createPlugin;
} catch(e) {
  createPlugin = require("/home/ibnu/.nvm/versions/node/v22.23.1/lib/node_modules/jonggrang/hooks/opencode/plugin.js").createPlugin;
}
// createPlugin returns { id, server, stub } — OpenCode calls server() when id is present
module.exports = createPlugin(projectRoot);